// AUTO-GENERATED by scripts/generate-manifest.js — do not hand-edit.
// Re-run `node scripts/generate-manifest.js` after adding/removing images.
window.PORTFOLIO_MANIFEST = {
  "about": [
    {
      "file": "about-portrait.jpg",
      "width": 1400,
      "height": 1750
    }
  ],
  "automobile": [
    {
      "file": "auto-01.jpg",
      "width": 1920,
      "height": 1280
    },
    {
      "file": "auto-02.jpg",
      "width": 1600,
      "height": 1200
    }
  ],
  "campaigns": [
    {
      "file": "campaign-01.jpg",
      "width": 1920,
      "height": 1280
    },
    {
      "file": "campaign-02.jpg",
      "width": 1600,
      "height": 1200
    },
    {
      "file": "campaign-03.jpg",
      "width": 1400,
      "height": 1750
    }
  ],
  "fashion": [
    {
      "file": "fashion-01.jpg",
      "width": 1400,
      "height": 1750
    },
    {
      "file": "fashion-02.jpg",
      "width": 1600,
      "height": 1200
    },
    {
      "file": "fashion-03.jpg",
      "width": 1400,
      "height": 1750
    }
  ],
  "food": [
    {
      "file": "food-01.jpg",
      "width": 1600,
      "height": 1200
    },
    {
      "file": "food-02.jpg",
      "width": 1400,
      "height": 1750
    },
    {
      "file": "food-03.jpg",
      "width": 1600,
      "height": 1200
    }
  ],
  "hero": [
    {
      "file": "hero-01.jpg",
      "width": 1920,
      "height": 1200
    }
  ],
  "hospitality": [
    {
      "file": "hospitality-01.jpg",
      "width": 1920,
      "height": 1280
    },
    {
      "file": "hospitality-02.jpg",
      "width": 1600,
      "height": 1200
    }
  ],
  "portraits": [
    {
      "file": "portrait-01.jpg",
      "width": 1400,
      "height": 1750
    },
    {
      "file": "portrait-02.jpg",
      "width": 1400,
      "height": 1750
    }
  ],
  "product": [
    {
      "file": "product-01.jpg",
      "width": 1600,
      "height": 1600
    },
    {
      "file": "product-02.jpg",
      "width": 1600,
      "height": 1200
    }
  ],
  "sports": [
    {
      "file": "sports-01.jpg",
      "width": 1600,
      "height": 1200
    },
    {
      "file": "sports-02.jpg",
      "width": 1400,
      "height": 1750
    }
  ]
};
